package api.sales.service.dto.internal;

public enum SalesChannel {
    WEBINAR, INBOUND, BASIC_ACCOUNT, BAP_MAILING, DOSSIER, RESEARCH_REQUEST, SEAL,
    COLD_CALL, CUSTOMER_VISIT, STROER, INDUSTRY_MAILING, COLD_MAILING, CONTENT_MARKETING, COOPERATION, LINKEDIN,
    FAIR,
    SPECIAL, EXISTING_CUSTOMER

}
